ca-cwds/cwds-jobs

build.gradle
jobs-facilities-cws/src/test/resources/fixtures/cwsrs_deleted_facility.json
jobs-facilities-cws/src/test/resources/fixtures/cwsrs_new_facility.json
jobs-facilities-cws/src/test/resources/fixtures/cwsrs_updated_facility.json
jobs-facilities-cws/src/test/resources/fixtures/facilities-initial-load-cwscms.json
jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lis/LisChangedFacilityService.java
jobs-facilities-lis/src/test/resources/fixtures/facilities-lis.json

Upgraded CALS API version
Facility ES Index rebuilding needed

SEAR-3 Unable to search for facility using complete Facility Address

---

build.gradle
jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/CwsFacilityJobModule.java

Integration new version of cals-api which has performance improvements

SEAR-198 Integration new version of cals-api

---

build.gradle
jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/identifier/CwsChangedEntitiesIdentifiersService.java
jobs-facilities-cws/src/test/resources/fixtures/cwsrs_deleted_facility.json
jobs-facilities-cws/src/test/resources/fixtures/cwsrs_new_facility.json
jobs-facilities-cws/src/test/resources/fixtures/cwsrs_updated_facility.json
jobs-facilities-cws/src/test/resources/fixtures/facilities-initial-load-cwscms.json
jobs-facilities-lis/src/test/resources/fixtures/facilities-lis.json

https://osi-cwds.atlassian.net/browse/SEAR-334
Addressed potential NullPointers in facility mappping
Addressed potential empty identifiers for CWS job
N/A

SEAR-334: Addressing NullPointer in Staging/Performance

---

build.gradle

Updated calsModelVersion and calsApiVersion to get license status dictionary values

SEAR-321 CALS-API-License-Status-Dictionary

---

build.gradle
jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/AbstractChangedFacilityService.java

SEAR-321: CALS-API-License-Status-Dictionary

---

jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/identifier/CwsChangedEntitiesIdentifiersService.java

removed empty identifiers handling

SEAR-321: removed empty identifiers handling

---

jobs-cap-users/src/main/resources/cap.users.mapping.json
jobs-cap-users/src/main/resources/cap.users.settings.json
jobs-cap-users/unix_cap_users_index.sh
jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticSearchIndexerDao.java

Add mappings and settings to sort users index case-insensitive.

Cog 363 add case insensitive sorting to users by name

---

build.gradle
jobs-facilities-lis/src/test/resources/fixtures/facilities-lis.json

https://osi-cwds.atlassian.net/browse/SEAR-363
Added leading zeroes to LIS license nyumber if needed

SEAR-363 fixed search by Facility Id with leading numbers

---

build.gradle

https://osi-cwds.atlassian.net/browse/COG-532
Upgraded Perry dependency
- [] I have included unit tests

COG-532 upgraded Perry dependency version to fetch last login timestamp

---

jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/CapUsersJobRunner.java
jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/AbstractChangedFacilityService.java
jobs-facilities-cws/cws_facility_index.bat
jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/CwsFacilityJobRunner.java
jobs-facilities-lis/lis_facility_index.bat
jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lisfas/LisFacilityJobRunner.java

https://osi-cwds.atlassian.net/browse/SEAR-319
Fixed config location issue

SEAR-319 fixed config location issue

---

build.gradle
jobs-cap-users/cap_users_index.bat
jobs-cap-users/unix_cap_users_index.sh
jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/AbstractChangedFacilityService.java
jobs-facilities-cws/cws_facility_index.bat
jobs-facilities-cws/unix_cws_facility_index.sh
jobs-facilities-lis/lis_facility_index.bat
jobs-facilities-lis/unix_lis_facility_index.sh

https://osi-cwds.atlassian.net/browse/SEAR-319
fixed sonar issue + upgraded major version. Major version increment is requested by DevOps ro reflect changes in configuration

SEAR-319 fixed sonar issue + upgraded major version

---

Jenkinsfile

adding SemVer

---

Jenkinsfile

test build triggered on pr merge

---

Jenkinsfile

Fit 291 implement semantic versioning support for cals job

---

build.gradle
jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/AbstractChangedFacilityService.java
jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/ChangedFacilityDto.java
jobs-facilities-common/src/test/java/gov/ca/cwds/jobs/cals/facility/ChangedFacilityDtoTest.java
jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/entity/CwsChangedFacilityService.java
jobs-facilities-cws/src/test/resources/fixtures/cwsrs_deleted_facility.json
jobs-facilities-cws/src/test/resources/fixtures/cwsrs_new_facility.json
jobs-facilities-cws/src/test/resources/fixtures/cwsrs_updated_facility.json
jobs-facilities-cws/src/test/resources/fixtures/facilities-initial-load-cwscms.json
jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lisfas/entity/LisChangedFacilityService.java
jobs-facilities-lis/src/test/resources/fixtures/facilities-lis.json

Upgrade cals-api dependency for facility jobs
Make minor changes needed for new dependency
[Get rid of column length restrictions for all the LIS data model classes](https://osi-cwds.atlassian.net/browse/SEAR-500)

SEAR-500: Get rid of column length restrictions for all the LIS data model classes

---

Jenkinsfile
build.gradle

Implement Semantic Versioning Support for cwds-jobs

Added Semantic Versioning and debug statements

---

Jenkinsfile

Implement Semantic Versioning Support for cwds-jobs

FIT-291 Implement Semantic Versioning Support for CALS-Job

---

Jenkinsfile
jobs-cap-users/build.gradle
jobs-facilities-cws/build.gradle
jobs-facilities-lis/build.gradle

Implement Semantic Versioning Support for cwds-jobs

 Implement Semantic Versioning Support for CALS Job, clean up

---

jobs-audit-events/audit_events_index.bat
jobs-audit-events/audit_events_index.sh
jobs-audit-events/build.gradle
jobs-audit-events/config/unix_audit-events-job.yaml
jobs-audit-events/log4j.properties
jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJobConfiguration.java
jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJobModule.java
jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJobModuleBuilder.java
jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJobRunner.java
jobs-audit-events/src/main/resources/audit.events.mapping.json
jobs-audit-events/src/main/resources/audit.events.settings.json
jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/AuditEventsJobTest.java
jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/event/AuditEvent.java
jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/event/CreatedEvent.java
jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/event/CustomEvent.java
jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/event/CustomEventTest.java
jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/event/NewValueSetEvent.java
jobs-audit-events/src/test/resources/audit-events-test.yaml
jobs-audit-events/src/test/resources/event1.json
jobs-audit-events/src/test/resources/event2.json
jobs-audit-events/src/test/resources/event3.json
settings.gradle

https://osi-cwds.atlassian.net/browse/COG-1071
Created console app for setting up general audit events index
Defined mapping for general audit event document type.
Added example of general audit event class 
New job introduced with configuration like below
```
elasticsearch:
elasticsearch.additional.nodes:
- localhost:9300
- localhost:9300
elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch}
elasticsearch.alias: ${ELASTIC_SEARCH_AUDIT_EVENTS_ALIAS:-auditevents}
elasticsearch.doctype: ${ELASTIC_SEARCH_AUDIT_EVENT_DOCTYPE:-auditevent}
elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9300}
#
elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}
```

COG-1071 Created console application for setting up auditevents ES index

---

Jenkinsfile

https://osi-cwds.atlassian.net/browse/FIT-375

(FIT-375) Modify CWDS Jobs CI Pipeline to support tagging for multiple artifacts

---

Jenkinsfile

https://osi-cwds.atlassian.net/browse/FIT-379

Moved build stage to the top and added toString() for build fix

---

jobs-audit-events/src/main/resources/audit.events.mapping.json

https://osi-cwds.atlassian.net/browse/COG-1097
Changed format of timestamp in auditevents index to adhere unified pattern yyyy-MM-dd HH:mm:ss

COG-1097 fixed date format

---

build.gradle

Perry dependency in CAP periodic job should be updated because of adding new notes field in User model.

COG-1182: Perry dependency version is updated

---

jobs-facilities-common/src/main/resources/facility.mapping.json
jobs-facilities-common/src/main/resources/facility.settings.json

- [Search fails if search term (facility name or facility address) has special characters in it without space in between](https://osi-cwds.atlassian.net/browse/SEAR-538)
Renamed analyzer from keyword to whitespace, added the analyzer to custom facility addresses i.e. residential and mailing

SEAR-538: renamed analyzer and added it to facility address

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

https://osi-cwds.atlassian.net/browse/FIT-415
Changed License Report plugin.
Increased gradle version, so the new plugin can run.

FIT-415 - Update Licensing Shared Library Component to produce CSV file for Java based projects

---

jobs-audit-events/config/unix_audit-events-job.yaml
jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventElasticWriter.java
jobs-audit-events/src/test/resources/audit-events-test.yaml
jobs-cap-users/config/unix_cap-users-job.yaml
jobs-cap-users/src/test/resources/cap-users-job-runner-test.yaml
jobs-cap-users/src/test/resources/cap-users-job-test.yaml
jobs-common/build.gradle
jobs-common/src/main/java/gov/ca/cwds/jobs/common/batch/BatchProcessor.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/util/SessionFactoryUtil.java
jobs-common/src/test/resources/testcases/testcase1/config.yaml
jobs-common/src/test/resources/testcases/testcase10/config.yaml
jobs-common/src/test/resources/testcases/testcase11/config.yaml
jobs-common/src/test/resources/testcases/testcase12/config.yaml
jobs-common/src/test/resources/testcases/testcase2/config.yaml
jobs-common/src/test/resources/testcases/testcase3/config.yaml
jobs-common/src/test/resources/testcases/testcase4/config.yaml
jobs-common/src/test/resources/testcases/testcase5/config.yaml
jobs-common/src/test/resources/testcases/testcase6/config.yaml
jobs-common/src/test/resources/testcases/testcase7/config.yaml
jobs-common/src/test/resources/testcases/testcase9/config.yaml
jobs-facilities-cws/config/cws-facility-job.yaml
jobs-facilities-cws/config/unix_cws_facility-job.yaml
jobs-facilities-cws/cws_facility_index.bat
jobs-facilities-cws/src/test/resources/cws-test-facility-job.yaml
jobs-facilities-cws/src/test/resources/cws-test-facility-jobrunner-test.yaml
jobs-facilities-cws/unix_cws_facility_index.sh
jobs-facilities-lis/config/lis-facility-job.yaml
jobs-facilities-lis/config/unix_lis-facility-job.yaml
jobs-facilities-lis/src/test/resources/lis-test-facility-job.yaml
jobs-facilities-lis/src/test/resources/lis-test-facility-jobrunner-test.yaml

https://osi-cwds.atlassian.net/browse/SEAR-563
https://osi-cwds.atlassian.net/browse/SEAR-563
Replaced c3p0 connection pool by hikari connection pool
Minor logging impovement 
Introducing Hikari connection pool

SEAR-563,SEAR-564 connection pool tuning for data sources

---

build.gradle

- https://osi-cwds.atlassian.net/browse/SEAR-560
Upgrading cals-jobs to fix version of cals-api

SEAR-560: Application Withdrawn and Application Denied status not showing

---

jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchService.java

SEAR-577 fixed sonar bug

---

jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/CapUsersJobModule.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchService.java
jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/BaseFacilityJobConfiguration.java
jobs-facilities-cws/src/test/resources/cws-test-facility-jobrunner-test.yaml
jobs-facilities-lis/src/test/resources/lis-test-facility-jobrunner-test.yaml

F### JIRA Issue Link
https://osi-cwds.atlassian.net/browse/SEAR-571
Fixed Cap Users job

SEAR-571 Fixed Cap Users job

---

build.gradle

SEAR-571 Trigger audit job release

---

jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventElasticWriter.java
jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/CapUsersWriter.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticWriter.java
jobs-facilities-common/src/main/java/gov/ca/cwds/jobs/cals/facility/FacilityElasticWriter.java

Fixed injection when creating elastic writers

SEAR-571 Fixed injection when creating elastic writers

---

jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/dto/ChangedUserDto.java
jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/job/CapUsersIncrementalUpdatesProcessor.java
jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/service/CwsChangedUsersServiceImpl.java
jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/service/IdmService.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/configuration/JobOptions.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/exception/JobExceptionHandler.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/identifier/ChangedEntityIdentifier.java
jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/CustomDb2Dialect.java
jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/CwdsJobsLimitHandler.java
jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/QueryConstants.java

https://osi-cwds.atlassian.net/browse/FIT-549
fixing sonar issues

FIT-549 Fix the critical and major code smells for Cals-jobs in Sonar cube

---

jobs-common/src/main/java/gov/ca/cwds/jobs/common/batch/BatchProcessor.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/inject/DataAccessModule.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/timereport/JobTimeReport.java
jobs-common/src/test/java/gov/ca/cwds/jobs/common/timereport/JobTimeReportTest.java

https://osi-cwds.atlassian.net/browse/FIT-549

Fix the critical and major code smells for Cals-jobs in Sonar cube

---

jobs-cap-users/src/test/java/gov/ca/cwds/jobs/cap/users/dto/ChangedUserDtoTest.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchService.java
jobs-common/src/test/java/gov/ca/cwds/jobs/common/elastic/ElasticUtilsTest.java
jobs-common/src/test/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchServiceTest.java
jobs-common/src/test/java/gov/ca/cwds/jobs/common/elastic/XPackUtilsTest.java

- https://osi-cwds.atlassian.net/browse/COG-1391
CWDS-Jobs: Increase test coverage to 70%

COG-1391: CWDS-Jobs: Increase test coverage to 70%

---

build.gradle

Trigger Job Release

---

build.gradle
jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/inject/CwsCmsRsDataAccessModule.java

- https://osi-cwds.atlassian.net/browse/SEAR-471
Facility Search email address of facility/home

SEAR-471: Facility search email address not showing in cws/cms - Update dependency

---

build.gradle
jobs-cap-users/src/main/resources/cap.users.mapping.json
jobs-cap-users/src/main/resources/cap.users.settings.json

- [COG-1340: Fuzzy Search for First Name and Last Name](https://osi-cwds.atlassian.net/browse/COG-1340)
Add index mapping for user first and last name for metaphone properties

Add subfield 'phonetic' to last_name and first_name of users index

---

jobs-audit-events/src/main/resources/audit.events.mapping.json
jobs-cap-users/src/main/resources/cap.users.mapping.json
jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticApiWrapper.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchService.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/inject/ElasticSearchModule.java
jobs-common/src/test/java/gov/ca/cwds/jobs/common/elastic/ElasticsearchServiceTest.java
jobs-facilities-common/src/main/resources/facility.mapping.json

https://osi-cwds.atlassian.net/browse/SEAR-133
cwds-job will issue exception once identified that custom mapping is not played properly. This will save time being spent on addressing the issue of having index with default mapping instead of custom mapping.

SEAR-133: Elastic Search index is not properly created

---

jobs-facilities-common/src/main/resources/facility.mapping.json
jobs-facilities-common/src/main/resources/facility.settings.json

https://osi-cwds.atlassian.net/browse/SEAR-579
Reverted back analyser for facility name field as it spoils sorting.  
Searching by special characters is likely to stop working

SEAR-579: Search results are not sort in alphabetical order

---

jobs-facilities-common/src/main/resources/facility.mapping.json
jobs-facilities-common/src/main/resources/facility.settings.json
jobs-facilities-cws/cws_facility_index.bat

https://osi-cwds.atlassian.net/browse/SEAR-579
Fixed mapping for facility index.  
Added back analyzer "whitespace_lowercase" for searching by special characters

SEAR-579: fixed sorting by facility name

---

jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJobModule.java
jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditEventsJobModuleBuilder.java
jobs-audit-events/src/test/java/gov/ca/cwds/jobs/audit/AuditEventsJobTest.java
jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/CapUsersJobModule.java
jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/CapUsersJobModuleBuilder.java
jobs-cap-users/src/main/java/gov/ca/cwds/jobs/cap/users/service/CapUsersSavePointService.java
jobs-cap-users/src/test/java/gov/ca/cwds/jobs/cap/users/CapUsersJobTest.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/inject/BaseContainerService.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/inject/ElasticSearchModule.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/inject/PrimaryContainerService.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/mode/AbstractJobModeService.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/mode/JobMode.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/mode/LocalDateTimeJobModeFinalizer.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/savepoint/IndexAwareSavePointContainerService.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/savepoint/LocalDateTimeSavePointService.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/savepoint/SavePointContainer.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/savepoint/SavePointServiceImpl.java
jobs-common/src/main/java/gov/ca/cwds/jobs/common/util/SavePointUtil.java
jobs-common/src/test/java/gov/ca/cwds/jobs/common/JobMainTest.java
jobs-common/src/test/java/gov/ca/cwds/jobs/common/TestCustomModule.java
jobs-common/src/test/java/gov/ca/cwds/jobs/common/mode/DefaultJobModeServiceTest.java
jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/CwsJobModuleBuilder.java
jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/inject/CwsFacilityJobModule.java
jobs-facilities-cws/src/test/java/gov/ca/cwds/jobs/cals/facility/cws/CwsFacilityJobTest.java
jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lisfas/LisJobModuleBuilder.java
jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lisfas/inject/LisFacilityJobModule.java
jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lisfas/mode/LisInitialJobModeFinalizer.java
jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lisfas/savepoint/LisTimestampSavePointService.java
jobs-facilities-lis/src/test/java/gov/ca/cwds/jobs/cals/facility/LisFacilityJobTest.java

https://osi-cwds.atlassian.net/browse/SEAR-606
Added information to savepoint about "ES index in progress" in order to be able to continue fulfilling ES index when resuming processing being stopped by error.

SEAR-606: cwds-jobs: Initial resume mode

---

jobs-audit-events/src/main/java/gov/ca/cwds/jobs/audit/AuditInitialJobModeFinalizer.java
jobs-facilities-cws/src/main/java/gov/ca/cwds/jobs/cals/facility/cws/CwsInitialJobModeFinalizer.java
jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lisfas/inject/LisFacilityJobModule.java
jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lisfas/savepoint/LicenseNumberSavePointService.java

https://osi-cwds.atlassian.net/browse/SEAR-606
Fixed several "index not saved in savepoint" bugs

SEAR-606: fixed "index not saved" bugs

---

code_climate_coverage_branch.sh
jenkinsfile-build-jobs.groovy
jenkinsfile-build.groovy
jobs-audit-events/build.gradle
jobs-cap-users/build.gradle
jobs-common/build.gradle
jobs-facilities-common/build.gradle
jobs-facilities-cws/build.gradle
jobs-facilities-lis/build.gradle

CMO- 523 : Configuring code climate.
Updated Jenkins pipeline to generate the jacoco test report for java files and updating into code climate server.

CMO-523: configured code climate and updating test coverage results.
